### ISSUE TITLE
add_edge!(g, u, v) add edge after throwing BoundsError

### ISSUE THREAD

**Issue by AsileBcd** [JuliaArchive/Graphs.jl#226]
I am new here, I am sorry if it is not the right place to post for that, but I have encountered a strange behavior (IMO).
The constructor add_edge!(g, u, v) is, as far as I understand, supposed to add an edge to an existing graph, conditional on:
- The source exists
- the target exists
  and throws a BoundsError otherwise. 
  What happens (with normally the latest build of Julia and Graphs is different: the BoundsError is thrown, but the edge is added nevertheless, without adding the corresponding vertices (which would be an acceptable behavior IMO). 
  Here is a simple code to reproduce the problem:

```
g = graph([1, 3], [])  ## Create a graph with 2 vertices and no edges
add_edge!(g, 2, 4)
e = Edge(1, 4, 2)
add_edge!(g, e)
edges(g)
```

I hope I am clear, if not, please tell me! Thank you.

**Comment by tkelman** [comment]
Don't know whether or not that's intentional, but just be aware of the activity level here - see https://github.com/JuliaLang/Graphs.jl/graphs/contributors.

You may want to look into https://github.com/JuliaGraphs/LightGraphs.jl instead which is more actively maintained.

**Comment by AsileBcd** [comment]
Thank you for the advice! Unfortunately, using the LightGraphs library seems very difficult for my purpose. I guess I will have to find another workaround!

**Comment by sbromberger** [comment]
@AsileBcd happy to advise if you want to open up an issue over in LightGraphs. It may wind up not being a good application for your specific problem, but we can certainly explore options.... I'll leave it up to you.

**Comment by AsileBcd** [comment]
Thank you! I will do that.
